### ISSUE TITLE
Support label selectors

### ISSUE THREAD

**Issue by Matt343** [ahmetb/kubectl-tree#21]
The tree command currently requires you to specify a single resource to use as the root. It would be helpful to instead be able to use a label selector (like `kubectl get -l`) and then build trees from each of the resources that match that selector.

**Comment by ahmetb** [comment]
This tool is currently a **single-rooted tree**, by design.

You can easily do

```
for res in $(kubectl get -l ...);  do
   kubectl tree "$res"
done
```

and make use of unix tool composability. :)

I don't want to open a can of worms like "what happens if one of the requests fail", "how do  we render multiple trees" etc.
