### ISSUE TITLE
would love to see ownership of files

### ISSUE THREAD

**Issue by rossayoung** [ahmetb/kubectl-tree#25]
Would love to see chmod type level characteristics of files.  Example tree command

tree -Cafp --prune /

**Comment by ahmetb** [comment]
How does this apply to Kubernetes?

**Comment by rossayoung** [comment]
if you are trying to ensure kubernetes security you would want to ensure certain files are owned and permissioned correctly.

**Comment by ahmetb** [comment]
I don't get it sorry. Kubernetes doesn't have anything to do with files. Furthermore this is not a security tool.
