### ISSUE TITLE
Could not find the cluster-scoped resource

### ISSUE THREAD

**Issue by ryysud** [ahmetb/kubectl-tree#26]
We are developing a Custom Controller and creating resources with the cluster-scoped CR set to OwnerReference, but `kubectl tree` doesn't work as bellow:

```bash
$ kubectl api-resources
NAME                              SHORTNAMES   APIGROUP                       NAMESPACED   KIND
samples                                        sample.example.org             false        Sample

$ kubectl tree samples sample -A
Error: failed to get samples/sample: the server could not find the requested resource
```

**Comment by ahmetb** [comment]
@feloy i think this is happening because of #22.

CRD here is not namespaced and user didn't specify -all-namespaces. 

Maybe if KIND is not namespaced, we should remove namespace filter. Wdyt?
