### ISSUE TITLE
Manual Install for WSL

### ISSUE THREAD

**Issue by JHBalaji** [ahmetb/kubectl-tree#31]
I did manual install for the krew and it seemed to work but again when installing this plugin I hit the same issue with path and permission denied.
How can I compile/install this bin in my WSL?

`Updated the local copy of plugin index.
Installing plugin: tree
W0506 11:06:06.719951    6465 install.go:138] failed to install plugin "tree": install failed: failed while moving files to the installation directory: could not rename/copy directory "/tmp/krew-temp-move234479147" to "/home/user_name/.krew/store/tree/v0.4.0": rename /tmp/krew-temp-move234479147 /home/user_name/.krew/store/tree/v0.4.0: permission denied
F0506 11:06:06.735376    6465 root.go:77] failed to install some plugins: [tree]: install failed: failed while moving files to the installation directory: could not rename/copy directory "/tmp/krew-temp-move234479147" to "/home/user_name/.krew/store/tree/v0.4.0": rename /tmp/krew-temp-move234479147 /home/user_name/.krew/store/tree/v0.4.0: permission denied`

**Comment by JHBalaji** [comment]
I copied the binary to the /home/user_name/.krew/store/tree/v0.4.0 and ran an upgrade. I was able to access the plugin as kubectl-tree for now.

**Comment by ahmetb** [comment]
It seems you were using Krew. Are you sure this path is writable?

Can you please try this:

```
mkdir -p /home/user_name/.krew/store/tree/0.4.0
```

and see if it works?

**Comment by JHBalaji** [comment]
> It seems you were using Krew. Are you sure this path is writable?
> 
> Can you please try this:
> 
> ```
> mkdir -p /home/user_name/.krew/store/tree/0.4.0
> ```
> 
> and see if it works?

Krew has path issues in WSL so most mount to root in C or use KREW_ROOT. Path is writable. [@159](https://github.com/kubernetes-sigs/krew/issues/159) helped me.

**Comment by ahmetb** [comment]
Please open an issue in Krew repo if any. I've tested it before with WSL and it has worked fine.
