### ISSUE TITLE
Show parents/ancestors option

### ISSUE THREAD

**Issue by tmshn** [ahmetb/kubectl-tree#37]
Hi, thank you for the great plugin!

This is a feature request/idea: how about offering an option to show resource parents/ancestors (i.e.: reverse hierarchy).
It's extremely useful when you have many CRDs and are confused which CR has others.

**Comment by ahmetb** [comment]
This is by design not supported so that the chosen object can be the root of the tree. Otherwise it might be part of a very large tree that might be hard to spot. ￼￼

**Comment by ahmetb** [comment]
Similarly an object might have more than one owner, in that case we don't wanna show multiple trees. ￼
