### ISSUE TITLE
Fails if privileges are limited

### ISSUE THREAD

**Issue by cbndr** [ahmetb/kubectl-tree#60]
In a production environment, users usually have limited privileges. In this case `kubectl tree <kind> <name>` fails with
```
Error: error while querying api objects: listing resources failed (<GVK>): <kind> is forbidden
```

I  would suggest to print a warning for 403s but continue processing otherwise.

EDIT: Just saw there is already https://github.com/ahmetb/kubectl-tree/pull/55 for this. Please merge.

**Comment by ahmetb** [comment]
Just pushed some changes to #55. Do you have the means to try that branch out and see if it works as you expected?
